// Creation de la route prise par les monstres au niveau 1 (si il y à d'autre niveau)
const roadMapLvl = [
  [
    ["borderTR", ["caseB7", "caseF15", "caseB18"]],
    [
      "borderTB",
      [
        "caseB1",
        "caseB2",
        "caseB3",
        "caseB4",
        "caseB5",
        "caseB6",
        "caseF6",
        "caseF5",
        "caseI5",
        "caseI6",
        "caseI7",
        "caseI8",
        "caseI9",
        "caseI10",
        "caseI11",
        "caseI12",
        "caseI13",
        "caseI14",
        "caseF14",
        "caseF13",
        "caseB13",
        "caseB14",
        "caseB15",
        "caseB16",
        "caseB17",
        "caseL17",
        "caseL16",
        "caseL15",
        "caseL14",
        "caseL13",
        "caseL12",
        "caseL11",
        "caseL10",
        "caseL9",
        "caseL8",
        "caseL7",
        "caseL6",
        "caseL5",
        "caseL4",
        "caseL3",
      ],
    ],
    ["borderTL", ["caseF4", "caseB12"]],
    ["borderBR", ["caseF7", "caseI15", "caseL18"]],
    ["borderBL", ["caseI4", "caseF12"]],
    [
      "borderLR",
      [
        "caseC7",
        "caseD7",
        "caseE7",
        "caseG4",
        "caseH4",
        "caseH15",
        "caseG15",
        "caseE12",
        "caseD12",
        "caseC12",
        "caseC18",
        "caseD18",
        "caseE18",
        "caseF18",
        "caseG18",
        "caseH18",
        "caseI18",
        "caseJ18",
        "caseK18",
      ],
    ],
  ],
  [
    ["borderTR", ["caseH12", "caseD12", "caseB17"]],
    [
      "borderTB",
      [
        "caseK4",
        "caseK5",
        "caseK6",
        "caseK7",
        "caseK8",
        "caseK9",
        "caseK10",
        "caseK11",
        "caseH11",
        "caseH10",
        "caseH9",
        "caseH8",
        "caseH7",
        "caseH6",
        "caseF6",
        "caseF7",
        "caseF8",
        "caseF9",
        "caseF10",
        "caseF11",
        "caseD11",
        "caseD10",
        "caseD9",
        "caseD8",
        "caseD7",
        "caseD6",
        "caseB6",
        "caseB7",
        "caseB8",
        "caseB9",
        "caseB10",
        "caseB11",
        "caseB12",
        "caseB13",
        "caseB14",
        "caseB15",
        "caseB16",
      ],
    ],
    ["borderTL", ["caseF5", "caseB5"]],
    ["borderBR", ["caseK12", "caseF12"]],
    ["borderBL", ["caseK3", "caseH5", "caseD5"]],
    [
      "borderLR",
      [
        "caseA3",
        "caseB3",
        "caseC3",
        "caseD3",
        "caseE3",
        "caseF3",
        "caseG3",
        "caseH3",
        "caseI3",
        "caseJ3",
        "caseJ12",
        "caseI12",
        "caseG5",
        "caseE12",
        "caseC5",
        "caseC17",
        "caseD17",
        "caseE17",
        "caseF17",
        "caseG17",
        "caseH17",
        "caseI17",
        "caseJ17",
      ],
    ],
  ],
];
const roadMobLvl = [
  [
    ["right", "caseB1"],
    ["bottom", "caseB7"],
    ["left", "caseF7"],
    ["bottom", "caseF4"],
    ["right", "caseI4"],
    ["top", "caseI15"],
    ["left", "caseF15"],
    ["top", "caseF12"],
    ["right", "caseB12"],
    ["bottom", "caseB18"],
    ["left", "caseL18"],
    ["default", "caseL2"],
  ],
  [
    ["bottom", "caseA3"],
    ["right", "caseK3"],
    ["top", "caseK12"],
    ["left", "caseH12"],
    ["top", "caseH5"],
    ["right", "caseF5"],
    ["top", "caseF12"],
    ["left", "caseD12"],
    ["top", "caseD5"],
    ["right", "caseB5"],
    ["bottom", "caseB17"],
    ["default", "caseK17"],
  ],
];
