// Creation de la route prise par les monstres au niveau 1 (si il y à d'autre niveau)
const roadMapLvl1 = [
  ["borderTR", ["caseB7", "caseF15", "caseB18"]],
  [
    "borderTB",
    [
      "caseB1",
      "caseB2",
      "caseB3",
      "caseB4",
      "caseB5",
      "caseB6",
      "caseF6",
      "caseF5",
      "caseI5",
      "caseI6",
      "caseI7",
      "caseI8",
      "caseI9",
      "caseI10",
      "caseI11",
      "caseI12",
      "caseI13",
      "caseI14",
      "caseF14",
      "caseF13",
      "caseB13",
      "caseB14",
      "caseB15",
      "caseB16",
      "caseB17",
      "caseL17",
      "caseL16",
      "caseL15",
      "caseL14",
      "caseL13",
      "caseL12",
      "caseL11",
      "caseL10",
      "caseL9",
      "caseL8",
      "caseL7",
      "caseL6",
      "caseL5",
      "caseL4",
      "caseL3",
    ],
  ],
  ["borderTL", ["caseF4", "caseB12"]],
  ["borderBR", ["caseF7", "caseI15", "caseL18"]],
  ["borderBL", ["caseI4", "caseF12"]],
  [
    "borderLR",
    [
      "caseC7",
      "caseD7",
      "caseE7",
      "caseG4",
      "caseH4",
      "caseH15",
      "caseG15",
      "caseE12",
      "caseD12",
      "caseC12",
      "caseC18",
      "caseD18",
      "caseE18",
      "caseF18",
      "caseG18",
      "caseH18",
      "caseI18",
      "caseJ18",
      "caseK18",
    ],
  ],
];
const roadMobLvl1 = [
  ["right", "caseB1"],
  ["bottom", "caseB7"],
  ["left", "caseF7"],
  ["bottom", "caseF4"],
  ["right", "caseI4"],
  ["top", "caseI15"],
  ["left", "caseF15"],
  ["top", "caseF12"],
  ["right", "caseB12"],
  ["bottom", "caseB18"],
  ["left", "caseL18"],
  ["right", "caseL2"],
];
//initialisation de tous les interval
